version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "infra"
    commit-message:
      prefix: "ci"

  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    labels:
      - "infra"
    commit-message:
      prefix: nuget
